### ISSUE TITLE
Documentation!?

### ISSUE THREAD

**Issue by appinteractive** [grand-stack/graphql-auth-directives#1]
- How can I use these directives? 
- What data structure they need? 
- How can I customize the logic / fields used?

Would be nice to some short examples. Thanks for the work! :)

**Comment by copleykj** [comment]
Yes, please! :smiley:

**Comment by johnymontana** [comment]
This has been addressed now in [the README](https://github.com/grand-stack/graphql-auth-directives/blob/master/README.md) and in [the GRANDstack docs](https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html#graphql-authorization-schema-directives). But please reopen if you feel some cases are not covered!

**Comment by thelovesmith** [comment]
The examples are still lacking for my use case. Still having trouble setting up authentication in my Grandstack app while following the readme and docs. Is there access to a full stack or completed app using these directives or just using authentication in GrandStack??
