### ISSUE TITLE
Error when using @hasScope directive

### ISSUE THREAD

**Issue by igokul1973** [grand-stack/graphql-auth-directives#9]
Hello again,

When using @hasScope directive, an error occurs when annotated by the directive fields are being resolved and the scope is being checked against expected. The bug lies on line `node_modules/graphql-auth-directives/dist/index.js:95` in the `HasScopeDirective` class where the `expectedScopes` point to the `this.args.roles` instead of the `this.args.scopes`:

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/5454915/65526642-1ced1300-defa-11e9-9fd5-bd9574e6c872.png">

Please fix it in the next release. FYI: I am using the latest version of your package as of today: 

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/5454915/65526752-4443e000-defa-11e9-9cf8-5193e4b55cc3.png">

**Comment by IamFlowZ** [comment]
I think this issue could be closed with my branch being merged.
